#!/usr/bin/python3
import sys


def factorize(n):
    '''
    find minimum number to devide
    '''
    i = 2

    while n % i:
        i += 1
    return (n/i, i)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()

    file = sys.argv[1]
    try:
        with open(file, 'r') as f:
            numbers = f.readlines()
    except FileNotFoundError:
        print("File not Found")
        exit()
    for number in numbers:
        iNum = int(number.strip())
        factors = factorize(iNum)
        if factors:
            print(f"{iNum}={int(factors[0])}*{factors[1]}")
